using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NestedObjects
{
    /// <summary>
    /// Represents an individual Course
    /// </summary>
    public class Course
    {
        /// <summary>
        /// Unique identifier for Courses
        /// This number is generated by the DB
        /// </summary>
        public int CourseID { get; set; }

        /// <summary>
        /// Title of a Course
        /// ex: Programming Fundamentals
        /// </summary>
        public string CourseTitle { get; set; }

        /// <summary>
        /// Text description of a Course
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Quarterly College Credit Hours Earned for a Course
        /// </summary>
        public byte Credits { get; set; }
    }
}
